# Trivium Jekyll theme general configurations

url: "http://rudrakos.com"

# Serving
detach:             false
port:               4000
host:               127.0.0.1
show_dir_listing:   false
baseurl:            ""

# include all different pages from _pages folder
include: [_pages]

# Trivium theme configuration. Please change accordingly.
trivium:
  name: Rudrakos
  # Little description about your site
  description: This is a personal site of Rahul Ranjan.
  meta_description: Rudrakos is a personal site of Rahul Ranjan.

  author: # Author details
    name: Rahul Ranjan
    email: rahul@rudrakos.com
    url: http://rudrakos.com/rahul

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-41921241-4
  # Addthis
  addthis_key: ra-56eccc9a39a92456
  # Disqus
  disqus_key: rudrakos

  # Profile links, leave blank to ignore
  social:
    github: rahulrrixe
    twitter: RahulRRixe
    facebook: rranjan93
    gplus: +RahulRanjan
    medium: RahulRRixe

  # Toggle disclaimer in footer
  show_disclaimer: true

# Conversion markdown build settings
markdown:           kramdown
highlighter:        rouge
lsi:                false
excerpt_separator:  "\n\n"
incremental:        false



# Permalinks
permalink: pretty

exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed

# collections
collections:
  projects:
    output: true
    permalink: /project/:path/
  categories:
    output: true
    permalink: /project/category/:path/

